site_name: native
site_description: native rest api
repo_url: https://github.com/dekanbro/dj-native
site_dir: site
copyright: Copyright &copy; 2018, <a href="https://github.com/dekanbro">dekanbro</a>.
dev_addr: 0.0.0.0:8001

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
